language: elixir
elixir: 1.0.0
env: MIX_ENV=test
notifications:
  recipients:
    - ldshuang@gmail.com
otp_release:
  - 17.4
before_install:
  - wget -q https://github.com/ideawu/ssdb/archive/master.zip
  - unzip master.zip
  - cd ssdb-master && make
  - ./ssdb-server -d ssdb.conf && cd ..
