language: erlang
notifications:
  recipients:
    - ldshuang@gmail.com
otp_release:
  - 17.1
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.0.zip
  - unzip -d elixir v1.0.0.zip
  - wget -q https://github.com/ideawu/ssdb/archive/master.zip
  - unzip master.zip
  - cd ssdb-master && make
  - ./ssdb-server -d ssdb.conf && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: "MIX_ENV=test mix test"
